// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: consensus/hbbft/hbbft.proto

package hbbft

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type PackagedSignal struct {
	BlockHeight int64 `protobuf:"varint,1,opt,name=block_height,json=blockHeight,proto3" json:"block_height,omitempty"`
}

func (m *PackagedSignal) Reset()         { *m = PackagedSignal{} }
func (m *PackagedSignal) String() string { return proto.CompactTextString(m) }
func (*PackagedSignal) ProtoMessage()    {}
func (*PackagedSignal) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b557cb8e095d7be, []int{0}
}
func (m *PackagedSignal) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *PackagedSignal) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_PackagedSignal.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *PackagedSignal) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PackagedSignal.Merge(m, src)
}
func (m *PackagedSignal) XXX_Size() int {
	return m.Size()
}
func (m *PackagedSignal) XXX_DiscardUnknown() {
	xxx_messageInfo_PackagedSignal.DiscardUnknown(m)
}

var xxx_messageInfo_PackagedSignal proto.InternalMessageInfo

func (m *PackagedSignal) GetBlockHeight() int64 {
	if m != nil {
		return m.BlockHeight
	}
	return 0
}

type TxBatchAfterABA struct {
	BlockHeight int64    `protobuf:"varint,1,opt,name=block_height,json=blockHeight,proto3" json:"block_height,omitempty"`
	TxBatchHash [][]byte `protobuf:"bytes,2,rep,name=tx_batch_hash,json=txBatchHash,proto3" json:"tx_batch_hash,omitempty"`
}

func (m *TxBatchAfterABA) Reset()         { *m = TxBatchAfterABA{} }
func (m *TxBatchAfterABA) String() string { return proto.CompactTextString(m) }
func (*TxBatchAfterABA) ProtoMessage()    {}
func (*TxBatchAfterABA) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b557cb8e095d7be, []int{1}
}
func (m *TxBatchAfterABA) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *TxBatchAfterABA) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_TxBatchAfterABA.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *TxBatchAfterABA) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TxBatchAfterABA.Merge(m, src)
}
func (m *TxBatchAfterABA) XXX_Size() int {
	return m.Size()
}
func (m *TxBatchAfterABA) XXX_DiscardUnknown() {
	xxx_messageInfo_TxBatchAfterABA.DiscardUnknown(m)
}

var xxx_messageInfo_TxBatchAfterABA proto.InternalMessageInfo

func (m *TxBatchAfterABA) GetBlockHeight() int64 {
	if m != nil {
		return m.BlockHeight
	}
	return 0
}

func (m *TxBatchAfterABA) GetTxBatchHash() [][]byte {
	if m != nil {
		return m.TxBatchHash
	}
	return nil
}

func init() {
	proto.RegisterType((*PackagedSignal)(nil), "hbbft.PackagedSignal")
	proto.RegisterType((*TxBatchAfterABA)(nil), "hbbft.TxBatchAfterABA")
}

func init() { proto.RegisterFile("consensus/hbbft/hbbft.proto", fileDescriptor_3b557cb8e095d7be) }

var fileDescriptor_3b557cb8e095d7be = []byte{
	// 216 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x4e, 0xce, 0xcf, 0x2b,
	0x4e, 0xcd, 0x2b, 0x2e, 0x2d, 0xd6, 0xcf, 0x48, 0x4a, 0x4a, 0x2b, 0x81, 0x90, 0x7a, 0x05, 0x45,
	0xf9, 0x25, 0xf9, 0x42, 0xac, 0x60, 0x8e, 0x92, 0x31, 0x17, 0x5f, 0x40, 0x62, 0x72, 0x76, 0x62,
	0x7a, 0x6a, 0x4a, 0x70, 0x66, 0x7a, 0x5e, 0x62, 0x8e, 0x90, 0x22, 0x17, 0x4f, 0x52, 0x4e, 0x7e,
	0x72, 0x76, 0x7c, 0x46, 0x6a, 0x66, 0x7a, 0x46, 0x89, 0x04, 0xa3, 0x02, 0xa3, 0x06, 0x73, 0x10,
	0x37, 0x58, 0xcc, 0x03, 0x2c, 0xa4, 0x14, 0xc1, 0xc5, 0x1f, 0x52, 0xe1, 0x94, 0x58, 0x92, 0x9c,
	0xe1, 0x98, 0x56, 0x92, 0x5a, 0xe4, 0xe8, 0xe4, 0x48, 0x84, 0x2e, 0x21, 0x25, 0x2e, 0xde, 0x92,
	0x8a, 0xf8, 0x24, 0x90, 0xb6, 0xf8, 0x8c, 0xc4, 0xe2, 0x0c, 0x09, 0x26, 0x05, 0x66, 0x0d, 0x9e,
	0x20, 0xee, 0x12, 0x88, 0x51, 0x1e, 0x89, 0xc5, 0x19, 0x4e, 0x81, 0x27, 0x1e, 0xc9, 0x31, 0x5e,
	0x78, 0x24, 0xc7, 0xf8, 0xe0, 0x91, 0x1c, 0xe3, 0x84, 0xc7, 0x72, 0x0c, 0x17, 0x1e, 0xcb, 0x31,
	0xdc, 0x78, 0x2c, 0xc7, 0x10, 0x65, 0x9e, 0x9c, 0x91, 0x98, 0x99, 0x97, 0x9b, 0x98, 0x9d, 0x5a,
	0xa4, 0x97, 0x5f, 0x94, 0xae, 0x8f, 0xe0, 0xea, 0xa6, 0xe7, 0xeb, 0x17, 0x24, 0xe9, 0x83, 0xbd,
	0x95, 0x9e, 0xaf, 0x8f, 0xe6, 0xe9, 0x24, 0x36, 0xb0, 0x84, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff,
	0x9a, 0xb4, 0xe5, 0xad, 0x0e, 0x01, 0x00, 0x00,
}

func (m *PackagedSignal) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *PackagedSignal) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *PackagedSignal) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.BlockHeight != 0 {
		i = encodeVarintHbbft(dAtA, i, uint64(m.BlockHeight))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *TxBatchAfterABA) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *TxBatchAfterABA) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *TxBatchAfterABA) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.TxBatchHash) > 0 {
		for iNdEx := len(m.TxBatchHash) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.TxBatchHash[iNdEx])
			copy(dAtA[i:], m.TxBatchHash[iNdEx])
			i = encodeVarintHbbft(dAtA, i, uint64(len(m.TxBatchHash[iNdEx])))
			i--
			dAtA[i] = 0x12
		}
	}
	if m.BlockHeight != 0 {
		i = encodeVarintHbbft(dAtA, i, uint64(m.BlockHeight))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintHbbft(dAtA []byte, offset int, v uint64) int {
	offset -= sovHbbft(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *PackagedSignal) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.BlockHeight != 0 {
		n += 1 + sovHbbft(uint64(m.BlockHeight))
	}
	return n
}

func (m *TxBatchAfterABA) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.BlockHeight != 0 {
		n += 1 + sovHbbft(uint64(m.BlockHeight))
	}
	if len(m.TxBatchHash) > 0 {
		for _, b := range m.TxBatchHash {
			l = len(b)
			n += 1 + l + sovHbbft(uint64(l))
		}
	}
	return n
}

func sovHbbft(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozHbbft(x uint64) (n int) {
	return sovHbbft(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *PackagedSignal) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowHbbft
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: PackagedSignal: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: PackagedSignal: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BlockHeight", wireType)
			}
			m.BlockHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowHbbft
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BlockHeight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipHbbft(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthHbbft
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *TxBatchAfterABA) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowHbbft
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: TxBatchAfterABA: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: TxBatchAfterABA: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BlockHeight", wireType)
			}
			m.BlockHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowHbbft
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BlockHeight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TxBatchHash", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowHbbft
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthHbbft
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthHbbft
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TxBatchHash = append(m.TxBatchHash, make([]byte, postIndex-iNdEx))
			copy(m.TxBatchHash[len(m.TxBatchHash)-1], dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipHbbft(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthHbbft
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipHbbft(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowHbbft
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowHbbft
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowHbbft
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthHbbft
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupHbbft
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthHbbft
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthHbbft        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowHbbft          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupHbbft = fmt.Errorf("proto: unexpected end of group")
)
