//
//Copyright (C) BABEC. All rights reserved.
//
//SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.0
// source: outside/contract.proto

package outside

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// smart contract runtime, contains vm type and language type
type RuntimeType int32

const (
	RuntimeType_INVALID RuntimeType = 0
	// native implement in chainmaker-go
	RuntimeType_NATIVE RuntimeType = 1
	// vm-wasmer, language-c++
	RuntimeType_WASMER RuntimeType = 2
	// vm-wxvm, language-cpp
	RuntimeType_WXVM RuntimeType = 3
	// wasm interpreter in go
	RuntimeType_GASM RuntimeType = 4
	// vm-evm
	RuntimeType_EVM RuntimeType = 5
	// vm-docker, language-golang
	RuntimeType_DOCKER_GO RuntimeType = 6
	// vm-docker, language-java
	RuntimeType_DOCKER_JAVA RuntimeType = 7
)

// Enum value maps for RuntimeType.
var (
	RuntimeType_name = map[int32]string{
		0: "INVALID",
		1: "NATIVE",
		2: "WASMER",
		3: "WXVM",
		4: "GASM",
		5: "EVM",
		6: "DOCKER_GO",
		7: "DOCKER_JAVA",
	}
	RuntimeType_value = map[string]int32{
		"INVALID":     0,
		"NATIVE":      1,
		"WASMER":      2,
		"WXVM":        3,
		"GASM":        4,
		"EVM":         5,
		"DOCKER_GO":   6,
		"DOCKER_JAVA": 7,
	}
)

func (x RuntimeType) Enum() *RuntimeType {
	p := new(RuntimeType)
	*p = x
	return p
}

func (x RuntimeType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RuntimeType) Descriptor() protoreflect.EnumDescriptor {
	return file_outside_contract_proto_enumTypes[0].Descriptor()
}

func (RuntimeType) Type() protoreflect.EnumType {
	return &file_outside_contract_proto_enumTypes[0]
}

func (x RuntimeType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RuntimeType.Descriptor instead.
func (RuntimeType) EnumDescriptor() ([]byte, []int) {
	return file_outside_contract_proto_rawDescGZIP(), []int{0}
}

// the unique identifier of a smart contract
type ContractId struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// smart contract name, set by contract creator, can have multiple versions
	ContractName string `protobuf:"bytes,1,opt,name=contract_name,json=contractName,proto3" json:"contract_name,omitempty"`
	// smart contract version, set by contract creator, name + version should be unique
	ContractVersion string `protobuf:"bytes,2,opt,name=contract_version,json=contractVersion,proto3" json:"contract_version,omitempty"`
	// smart contract runtime type, set by contract creator
	RuntimeType RuntimeType `protobuf:"varint,3,opt,name=runtime_type,json=runtimeType,proto3,enum=outside.RuntimeType" json:"runtime_type,omitempty"`
}

func (x *ContractId) Reset() {
	*x = ContractId{}
	if protoimpl.UnsafeEnabled {
		mi := &file_outside_contract_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ContractId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContractId) ProtoMessage() {}

func (x *ContractId) ProtoReflect() protoreflect.Message {
	mi := &file_outside_contract_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContractId.ProtoReflect.Descriptor instead.
func (*ContractId) Descriptor() ([]byte, []int) {
	return file_outside_contract_proto_rawDescGZIP(), []int{0}
}

func (x *ContractId) GetContractName() string {
	if x != nil {
		return x.ContractName
	}
	return ""
}

func (x *ContractId) GetContractVersion() string {
	if x != nil {
		return x.ContractVersion
	}
	return ""
}

func (x *ContractId) GetRuntimeType() RuntimeType {
	if x != nil {
		return x.RuntimeType
	}
	return RuntimeType_INVALID
}

var File_outside_contract_proto protoreflect.FileDescriptor

var file_outside_contract_proto_rawDesc = []byte{
	0x0a, 0x16, 0x6f, 0x75, 0x74, 0x73, 0x69, 0x64, 0x65, 0x2f, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61,
	0x63, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x6f, 0x75, 0x74, 0x73, 0x69, 0x64,
	0x65, 0x22, 0x95, 0x01, 0x0a, 0x0a, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x49, 0x64,
	0x12, 0x23, 0x0a, 0x0d, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x5f, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63,
	0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x29, 0x0a, 0x10, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63,
	0x74, 0x5f, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0f, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e,
	0x12, 0x37, 0x0a, 0x0c, 0x72, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x5f, 0x74, 0x79, 0x70, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x14, 0x2e, 0x6f, 0x75, 0x74, 0x73, 0x69, 0x64, 0x65,
	0x2e, 0x52, 0x75, 0x6e, 0x74, 0x69, 0x6d, 0x65, 0x54, 0x79, 0x70, 0x65, 0x52, 0x0b, 0x72, 0x75,
	0x6e, 0x74, 0x69, 0x6d, 0x65, 0x54, 0x79, 0x70, 0x65, 0x2a, 0x6f, 0x0a, 0x0b, 0x52, 0x75, 0x6e,
	0x74, 0x69, 0x6d, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0b, 0x0a, 0x07, 0x49, 0x4e, 0x56, 0x41,
	0x4c, 0x49, 0x44, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x4e, 0x41, 0x54, 0x49, 0x56, 0x45, 0x10,
	0x01, 0x12, 0x0a, 0x0a, 0x06, 0x57, 0x41, 0x53, 0x4d, 0x45, 0x52, 0x10, 0x02, 0x12, 0x08, 0x0a,
	0x04, 0x57, 0x58, 0x56, 0x4d, 0x10, 0x03, 0x12, 0x08, 0x0a, 0x04, 0x47, 0x41, 0x53, 0x4d, 0x10,
	0x04, 0x12, 0x07, 0x0a, 0x03, 0x45, 0x56, 0x4d, 0x10, 0x05, 0x12, 0x0d, 0x0a, 0x09, 0x44, 0x4f,
	0x43, 0x4b, 0x45, 0x52, 0x5f, 0x47, 0x4f, 0x10, 0x06, 0x12, 0x0f, 0x0a, 0x0b, 0x44, 0x4f, 0x43,
	0x4b, 0x45, 0x52, 0x5f, 0x4a, 0x41, 0x56, 0x41, 0x10, 0x07, 0x42, 0x4b, 0x5a, 0x49, 0x63, 0x68,
	0x61, 0x69, 0x6e, 0x6d, 0x61, 0x6b, 0x65, 0x72, 0x2e, 0x6f, 0x72, 0x67, 0x2f, 0x63, 0x68, 0x61,
	0x69, 0x6e, 0x6d, 0x61, 0x6b, 0x65, 0x72, 0x2d, 0x67, 0x6f, 0x2f, 0x64, 0x6f, 0x63, 0x6b, 0x65,
	0x72, 0x2d, 0x67, 0x6f, 0x2f, 0x64, 0x6f, 0x63, 0x6b, 0x65, 0x72, 0x63, 0x6f, 0x6e, 0x74, 0x61,
	0x69, 0x6e, 0x65, 0x72, 0x2f, 0x70, 0x62, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x67, 0x6f, 0x2f,
	0x6f, 0x75, 0x74, 0x73, 0x69, 0x64, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_outside_contract_proto_rawDescOnce sync.Once
	file_outside_contract_proto_rawDescData = file_outside_contract_proto_rawDesc
)

func file_outside_contract_proto_rawDescGZIP() []byte {
	file_outside_contract_proto_rawDescOnce.Do(func() {
		file_outside_contract_proto_rawDescData = protoimpl.X.CompressGZIP(file_outside_contract_proto_rawDescData)
	})
	return file_outside_contract_proto_rawDescData
}

var file_outside_contract_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_outside_contract_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_outside_contract_proto_goTypes = []interface{}{
	(RuntimeType)(0),   // 0: outside.RuntimeType
	(*ContractId)(nil), // 1: outside.ContractId
}
var file_outside_contract_proto_depIdxs = []int32{
	0, // 0: outside.ContractId.runtime_type:type_name -> outside.RuntimeType
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_outside_contract_proto_init() }
func file_outside_contract_proto_init() {
	if File_outside_contract_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_outside_contract_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ContractId); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_outside_contract_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_outside_contract_proto_goTypes,
		DependencyIndexes: file_outside_contract_proto_depIdxs,
		EnumInfos:         file_outside_contract_proto_enumTypes,
		MessageInfos:      file_outside_contract_proto_msgTypes,
	}.Build()
	File_outside_contract_proto = out.File
	file_outside_contract_proto_rawDesc = nil
	file_outside_contract_proto_goTypes = nil
	file_outside_contract_proto_depIdxs = nil
}
