//
//Copyright (C) BABEC. All rights reserved.
//
//SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.0
// source: api/docker_rpc.proto

package api

import (
	outside "chainmaker.org/chainmaker-go/docker-go/dockercontainer/pb/protogo/outside"
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_api_docker_rpc_proto protoreflect.FileDescriptor

var file_api_docker_rpc_proto_rawDesc = []byte{
	0x0a, 0x14, 0x61, 0x70, 0x69, 0x2f, 0x64, 0x6f, 0x63, 0x6b, 0x65, 0x72, 0x5f, 0x72, 0x70, 0x63,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x61, 0x70, 0x69, 0x1a, 0x15, 0x6f, 0x75, 0x74,
	0x73, 0x69, 0x64, 0x65, 0x2f, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x1a, 0x14, 0x6f, 0x75, 0x74, 0x73, 0x69, 0x64, 0x65, 0x2f, 0x72, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x32, 0x46, 0x0a, 0x09, 0x44, 0x6f, 0x63, 0x6b,
	0x65, 0x72, 0x52, 0x70, 0x63, 0x12, 0x39, 0x0a, 0x0c, 0x52, 0x75, 0x6e, 0x43, 0x6f, 0x6e, 0x74,
	0x72, 0x61, 0x63, 0x74, 0x73, 0x12, 0x12, 0x2e, 0x6f, 0x75, 0x74, 0x73, 0x69, 0x64, 0x65, 0x2e,
	0x54, 0x78, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x11, 0x2e, 0x6f, 0x75, 0x74, 0x73,
	0x69, 0x64, 0x65, 0x2e, 0x54, 0x78, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x00, 0x28, 0x01,
	0x42, 0x47, 0x5a, 0x45, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x6d, 0x61, 0x6b, 0x65, 0x72, 0x2e, 0x6f,
	0x72, 0x67, 0x2f, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x6d, 0x61, 0x6b, 0x65, 0x72, 0x2d, 0x67, 0x6f,
	0x2f, 0x64, 0x6f, 0x63, 0x6b, 0x65, 0x72, 0x2d, 0x67, 0x6f, 0x2f, 0x64, 0x6f, 0x63, 0x6b, 0x65,
	0x72, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x2f, 0x70, 0x62, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x67, 0x6f, 0x2f, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var file_api_docker_rpc_proto_goTypes = []interface{}{
	(*outside.TxRequest)(nil), // 0: outside.TxRequest
	(*outside.TxResult)(nil),  // 1: outside.TxResult
}
var file_api_docker_rpc_proto_depIdxs = []int32{
	0, // 0: api.DockerRpc.RunContracts:input_type -> outside.TxRequest
	1, // 1: api.DockerRpc.RunContracts:output_type -> outside.TxResult
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_docker_rpc_proto_init() }
func file_api_docker_rpc_proto_init() {
	if File_api_docker_rpc_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_docker_rpc_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_docker_rpc_proto_goTypes,
		DependencyIndexes: file_api_docker_rpc_proto_depIdxs,
	}.Build()
	File_api_docker_rpc_proto = out.File
	file_api_docker_rpc_proto_rawDesc = nil
	file_api_docker_rpc_proto_goTypes = nil
	file_api_docker_rpc_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// DockerRpcClient is the client API for DockerRpc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DockerRpcClient interface {
	RunContracts(ctx context.Context, opts ...grpc.CallOption) (DockerRpc_RunContractsClient, error)
}

type dockerRpcClient struct {
	cc grpc.ClientConnInterface
}

func NewDockerRpcClient(cc grpc.ClientConnInterface) DockerRpcClient {
	return &dockerRpcClient{cc}
}

func (c *dockerRpcClient) RunContracts(ctx context.Context, opts ...grpc.CallOption) (DockerRpc_RunContractsClient, error) {
	stream, err := c.cc.NewStream(ctx, &_DockerRpc_serviceDesc.Streams[0], "/api.DockerRpc/RunContracts", opts...)
	if err != nil {
		return nil, err
	}
	x := &dockerRpcRunContractsClient{stream}
	return x, nil
}

type DockerRpc_RunContractsClient interface {
	Send(*outside.TxRequest) error
	CloseAndRecv() (*outside.TxResult, error)
	grpc.ClientStream
}

type dockerRpcRunContractsClient struct {
	grpc.ClientStream
}

func (x *dockerRpcRunContractsClient) Send(m *outside.TxRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *dockerRpcRunContractsClient) CloseAndRecv() (*outside.TxResult, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(outside.TxResult)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// DockerRpcServer is the server API for DockerRpc service.
type DockerRpcServer interface {
	RunContracts(DockerRpc_RunContractsServer) error
}

// UnimplementedDockerRpcServer can be embedded to have forward compatible implementations.
type UnimplementedDockerRpcServer struct {
}

func (*UnimplementedDockerRpcServer) RunContracts(DockerRpc_RunContractsServer) error {
	return status.Errorf(codes.Unimplemented, "method RunContracts not implemented")
}

func RegisterDockerRpcServer(s *grpc.Server, srv DockerRpcServer) {
	s.RegisterService(&_DockerRpc_serviceDesc, srv)
}

func _DockerRpc_RunContracts_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(DockerRpcServer).RunContracts(&dockerRpcRunContractsServer{stream})
}

type DockerRpc_RunContractsServer interface {
	SendAndClose(*outside.TxResult) error
	Recv() (*outside.TxRequest, error)
	grpc.ServerStream
}

type dockerRpcRunContractsServer struct {
	grpc.ServerStream
}

func (x *dockerRpcRunContractsServer) SendAndClose(m *outside.TxResult) error {
	return x.ServerStream.SendMsg(m)
}

func (x *dockerRpcRunContractsServer) Recv() (*outside.TxRequest, error) {
	m := new(outside.TxRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _DockerRpc_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.DockerRpc",
	HandlerType: (*DockerRpcServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "RunContracts",
			Handler:       _DockerRpc_RunContracts_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "api/docker_rpc.proto",
}
