//
//Copyright (C) BABEC. All rights reserved.
//
//SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.0
// source: api/docker_rpc.proto

package api

import (
	outside "chainmaker.org/chainmaker-go/docker-go/dockercontainer/pb/protogo/outside"
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_api_docker_rpc_proto protoreflect.FileDescriptor

var file_api_docker_rpc_proto_rawDesc = []byte{
	0x0a, 0x14, 0x61, 0x70, 0x69, 0x2f, 0x64, 0x6f, 0x63, 0x6b, 0x65, 0x72, 0x5f, 0x72, 0x70, 0x63,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x61, 0x70, 0x69, 0x1a, 0x15, 0x6f, 0x75, 0x74,
	0x73, 0x69, 0x64, 0x65, 0x2f, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x1a, 0x14, 0x6f, 0x75, 0x74, 0x73, 0x69, 0x64, 0x65, 0x2f, 0x72, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x32, 0x4a, 0x0a, 0x09, 0x44, 0x6f, 0x63, 0x6b,
	0x65, 0x72, 0x52, 0x70, 0x63, 0x12, 0x3d, 0x0a, 0x0c, 0x52, 0x75, 0x6e, 0x43, 0x6f, 0x6e, 0x74,
	0x72, 0x61, 0x63, 0x74, 0x73, 0x12, 0x12, 0x2e, 0x6f, 0x75, 0x74, 0x73, 0x69, 0x64, 0x65, 0x2e,
	0x54, 0x78, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x6f, 0x75, 0x74, 0x73,
	0x69, 0x64, 0x65, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x52, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x22, 0x00, 0x42, 0x47, 0x5a, 0x45, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x6d, 0x61, 0x6b,
	0x65, 0x72, 0x2e, 0x6f, 0x72, 0x67, 0x2f, 0x63, 0x68, 0x61, 0x69, 0x6e, 0x6d, 0x61, 0x6b, 0x65,
	0x72, 0x2d, 0x67, 0x6f, 0x2f, 0x64, 0x6f, 0x63, 0x6b, 0x65, 0x72, 0x2d, 0x67, 0x6f, 0x2f, 0x64,
	0x6f, 0x63, 0x6b, 0x65, 0x72, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x2f, 0x70,
	0x62, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x67, 0x6f, 0x2f, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var file_api_docker_rpc_proto_goTypes = []interface{}{
	(*outside.TxRequest)(nil),      // 0: outside.TxRequest
	(*outside.ContractResult)(nil), // 1: outside.ContractResult
}
var file_api_docker_rpc_proto_depIdxs = []int32{
	0, // 0: api.DockerRpc.RunContracts:input_type -> outside.TxRequest
	1, // 1: api.DockerRpc.RunContracts:output_type -> outside.ContractResult
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_docker_rpc_proto_init() }
func file_api_docker_rpc_proto_init() {
	if File_api_docker_rpc_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_docker_rpc_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_docker_rpc_proto_goTypes,
		DependencyIndexes: file_api_docker_rpc_proto_depIdxs,
	}.Build()
	File_api_docker_rpc_proto = out.File
	file_api_docker_rpc_proto_rawDesc = nil
	file_api_docker_rpc_proto_goTypes = nil
	file_api_docker_rpc_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// DockerRpcClient is the client API for DockerRpc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DockerRpcClient interface {
	RunContracts(ctx context.Context, in *outside.TxRequest, opts ...grpc.CallOption) (*outside.ContractResult, error)
}

type dockerRpcClient struct {
	cc grpc.ClientConnInterface
}

func NewDockerRpcClient(cc grpc.ClientConnInterface) DockerRpcClient {
	return &dockerRpcClient{cc}
}

func (c *dockerRpcClient) RunContracts(ctx context.Context, in *outside.TxRequest, opts ...grpc.CallOption) (*outside.ContractResult, error) {
	out := new(outside.ContractResult)
	err := c.cc.Invoke(ctx, "/api.DockerRpc/RunContracts", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DockerRpcServer is the server API for DockerRpc service.
type DockerRpcServer interface {
	RunContracts(context.Context, *outside.TxRequest) (*outside.ContractResult, error)
}

// UnimplementedDockerRpcServer can be embedded to have forward compatible implementations.
type UnimplementedDockerRpcServer struct {
}

func (*UnimplementedDockerRpcServer) RunContracts(context.Context, *outside.TxRequest) (*outside.ContractResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RunContracts not implemented")
}

func RegisterDockerRpcServer(s *grpc.Server, srv DockerRpcServer) {
	s.RegisterService(&_DockerRpc_serviceDesc, srv)
}

func _DockerRpc_RunContracts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(outside.TxRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DockerRpcServer).RunContracts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.DockerRpc/RunContracts",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DockerRpcServer).RunContracts(ctx, req.(*outside.TxRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _DockerRpc_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.DockerRpc",
	HandlerType: (*DockerRpcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RunContracts",
			Handler:    _DockerRpc_RunContracts_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/docker_rpc.proto",
}
