// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: cdm_message.proto

package protogo

import (
	context "context"
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type CDMType int32

const (
	CDMType_CDM_TYPE_UNDEFINED             CDMType = 0
	CDMType_CDM_TYPE_TX_REQUEST            CDMType = 1
	CDMType_CDM_TYPE_TX_RESPONSE           CDMType = 2
	CDMType_CDM_TYPE_GET_STATE             CDMType = 3
	CDMType_CDM_TYPE_GET_STATE_RESPONSE    CDMType = 4
	CDMType_CDM_TYPE_GET_BYTECODE          CDMType = 5
	CDMType_CDM_TYPE_GET_BYTECODE_RESPONSE CDMType = 6
)

var CDMType_name = map[int32]string{
	0: "CDM_TYPE_UNDEFINED",
	1: "CDM_TYPE_TX_REQUEST",
	2: "CDM_TYPE_TX_RESPONSE",
	3: "CDM_TYPE_GET_STATE",
	4: "CDM_TYPE_GET_STATE_RESPONSE",
	5: "CDM_TYPE_GET_BYTECODE",
	6: "CDM_TYPE_GET_BYTECODE_RESPONSE",
}

var CDMType_value = map[string]int32{
	"CDM_TYPE_UNDEFINED":             0,
	"CDM_TYPE_TX_REQUEST":            1,
	"CDM_TYPE_TX_RESPONSE":           2,
	"CDM_TYPE_GET_STATE":             3,
	"CDM_TYPE_GET_STATE_RESPONSE":    4,
	"CDM_TYPE_GET_BYTECODE":          5,
	"CDM_TYPE_GET_BYTECODE_RESPONSE": 6,
}

func (x CDMType) String() string {
	return proto.EnumName(CDMType_name, int32(x))
}

func (CDMType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_797a9ac5b2994f84, []int{0}
}

type ContractResultCode int32

const (
	ContractResultCode_OK   ContractResultCode = 0
	ContractResultCode_FAIL ContractResultCode = 1
)

var ContractResultCode_name = map[int32]string{
	0: "OK",
	1: "FAIL",
}

var ContractResultCode_value = map[string]int32{
	"OK":   0,
	"FAIL": 1,
}

func (x ContractResultCode) String() string {
	return proto.EnumName(ContractResultCode_name, int32(x))
}

func (ContractResultCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_797a9ac5b2994f84, []int{1}
}

//CMMessage means message between chainmaker and docker manager
type CDMMessage struct {
	TxId    string  `protobuf:"bytes,1,opt,name=tx_id,json=txId,proto3" json:"tx_id,omitempty"`
	Type    CDMType `protobuf:"varint,2,opt,name=type,proto3,enum=proto.CDMType" json:"type,omitempty"`
	Payload []byte  `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
}

func (m *CDMMessage) Reset()         { *m = CDMMessage{} }
func (m *CDMMessage) String() string { return proto.CompactTextString(m) }
func (*CDMMessage) ProtoMessage()    {}
func (*CDMMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_797a9ac5b2994f84, []int{0}
}
func (m *CDMMessage) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *CDMMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_CDMMessage.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *CDMMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CDMMessage.Merge(m, src)
}
func (m *CDMMessage) XXX_Size() int {
	return m.Size()
}
func (m *CDMMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_CDMMessage.DiscardUnknown(m)
}

var xxx_messageInfo_CDMMessage proto.InternalMessageInfo

func (m *CDMMessage) GetTxId() string {
	if m != nil {
		return m.TxId
	}
	return ""
}

func (m *CDMMessage) GetType() CDMType {
	if m != nil {
		return m.Type
	}
	return CDMType_CDM_TYPE_UNDEFINED
}

func (m *CDMMessage) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

// tx request - TX_REQUEST
type TxRequest struct {
	TxId            string            `protobuf:"bytes,1,opt,name=tx_id,json=txId,proto3" json:"tx_id,omitempty"`
	ContractName    string            `protobuf:"bytes,2,opt,name=contract_name,json=contractName,proto3" json:"contract_name,omitempty"`
	ContractVersion string            `protobuf:"bytes,3,opt,name=contract_version,json=contractVersion,proto3" json:"contract_version,omitempty"`
	Method          string            `protobuf:"bytes,4,opt,name=method,proto3" json:"method,omitempty"`
	ByteCode        []byte            `protobuf:"bytes,5,opt,name=byteCode,proto3" json:"byteCode,omitempty"`
	Parameters      map[string]string `protobuf:"bytes,6,rep,name=parameters,proto3" json:"parameters,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (m *TxRequest) Reset()         { *m = TxRequest{} }
func (m *TxRequest) String() string { return proto.CompactTextString(m) }
func (*TxRequest) ProtoMessage()    {}
func (*TxRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_797a9ac5b2994f84, []int{1}
}
func (m *TxRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *TxRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_TxRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *TxRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TxRequest.Merge(m, src)
}
func (m *TxRequest) XXX_Size() int {
	return m.Size()
}
func (m *TxRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TxRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TxRequest proto.InternalMessageInfo

func (m *TxRequest) GetTxId() string {
	if m != nil {
		return m.TxId
	}
	return ""
}

func (m *TxRequest) GetContractName() string {
	if m != nil {
		return m.ContractName
	}
	return ""
}

func (m *TxRequest) GetContractVersion() string {
	if m != nil {
		return m.ContractVersion
	}
	return ""
}

func (m *TxRequest) GetMethod() string {
	if m != nil {
		return m.Method
	}
	return ""
}

func (m *TxRequest) GetByteCode() []byte {
	if m != nil {
		return m.ByteCode
	}
	return nil
}

func (m *TxRequest) GetParameters() map[string]string {
	if m != nil {
		return m.Parameters
	}
	return nil
}

// tx response - TX_RESPONSE
type TxResponse struct {
	TxId    string             `protobuf:"bytes,1,opt,name=tx_id,json=txId,proto3" json:"tx_id,omitempty"`
	Code    ContractResultCode `protobuf:"varint,2,opt,name=code,proto3,enum=proto.ContractResultCode" json:"code,omitempty"`
	Result  []byte             `protobuf:"bytes,3,opt,name=result,proto3" json:"result,omitempty"`
	Message string             `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
}

func (m *TxResponse) Reset()         { *m = TxResponse{} }
func (m *TxResponse) String() string { return proto.CompactTextString(m) }
func (*TxResponse) ProtoMessage()    {}
func (*TxResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_797a9ac5b2994f84, []int{2}
}
func (m *TxResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *TxResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_TxResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *TxResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TxResponse.Merge(m, src)
}
func (m *TxResponse) XXX_Size() int {
	return m.Size()
}
func (m *TxResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TxResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TxResponse proto.InternalMessageInfo

func (m *TxResponse) GetTxId() string {
	if m != nil {
		return m.TxId
	}
	return ""
}

func (m *TxResponse) GetCode() ContractResultCode {
	if m != nil {
		return m.Code
	}
	return ContractResultCode_OK
}

func (m *TxResponse) GetResult() []byte {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *TxResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterEnum("proto.CDMType", CDMType_name, CDMType_value)
	proto.RegisterEnum("proto.ContractResultCode", ContractResultCode_name, ContractResultCode_value)
	proto.RegisterType((*CDMMessage)(nil), "proto.CDMMessage")
	proto.RegisterType((*TxRequest)(nil), "proto.TxRequest")
	proto.RegisterMapType((map[string]string)(nil), "proto.TxRequest.ParametersEntry")
	proto.RegisterType((*TxResponse)(nil), "proto.TxResponse")
}

func init() { proto.RegisterFile("cdm_message.proto", fileDescriptor_797a9ac5b2994f84) }

var fileDescriptor_797a9ac5b2994f84 = []byte{
	// 575 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x53, 0x5f, 0x4f, 0xd3, 0x50,
	0x14, 0xef, 0xdd, 0xba, 0xc2, 0x8e, 0x08, 0xe5, 0x82, 0x58, 0x30, 0xa9, 0x4b, 0x4d, 0xcc, 0x24,
	0x61, 0x33, 0xf8, 0x62, 0x8c, 0x26, 0x42, 0x5b, 0x0c, 0xd1, 0x0e, 0xec, 0x8a, 0x11, 0x7d, 0x68,
	0x2e, 0xed, 0xcd, 0x58, 0xa0, 0xbd, 0xb5, 0xbd, 0x23, 0xf4, 0xd5, 0x4f, 0xe0, 0x97, 0xf0, 0xbb,
	0xf8, 0xe0, 0x03, 0x8f, 0x3e, 0x1a, 0xf8, 0x22, 0xa6, 0xff, 0x36, 0xe7, 0xf0, 0xa9, 0xe7, 0xf7,
	0x3b, 0xe7, 0xf4, 0xfc, 0xf9, 0x9d, 0x0b, 0xcb, 0x9e, 0x1f, 0xb8, 0x01, 0x4d, 0x12, 0x32, 0xa0,
	0x9d, 0x28, 0x66, 0x9c, 0xe1, 0x46, 0xfe, 0xd1, 0x5c, 0x00, 0xdd, 0xb0, 0xac, 0xc2, 0x85, 0x57,
	0xa0, 0xc1, 0x2f, 0xdd, 0xa1, 0xaf, 0xa0, 0x16, 0x6a, 0x37, 0x6d, 0x91, 0x5f, 0xee, 0xfb, 0x58,
	0x03, 0x91, 0xa7, 0x11, 0x55, 0x6a, 0x2d, 0xd4, 0x5e, 0xdc, 0x5e, 0x2c, 0xf2, 0x3b, 0xba, 0x61,
	0x39, 0x69, 0x44, 0xed, 0xdc, 0x87, 0x15, 0x98, 0x8b, 0x48, 0x7a, 0xce, 0x88, 0xaf, 0xd4, 0x5b,
	0xa8, 0xbd, 0x60, 0x57, 0x50, 0xfb, 0x5e, 0x83, 0xa6, 0x73, 0x69, 0xd3, 0x2f, 0x23, 0x9a, 0xf0,
	0xdb, 0x0b, 0x3c, 0x82, 0xbb, 0x1e, 0x0b, 0x79, 0x4c, 0x3c, 0xee, 0x86, 0x24, 0x28, 0x2a, 0x35,
	0xed, 0x85, 0x8a, 0xec, 0x91, 0x80, 0xe2, 0x27, 0x20, 0x8f, 0x83, 0x2e, 0x68, 0x9c, 0x0c, 0x59,
	0x98, 0x97, 0x6a, 0xda, 0x4b, 0x15, 0xff, 0xa1, 0xa0, 0xf1, 0x1a, 0x48, 0x01, 0xe5, 0xa7, 0xcc,
	0x57, 0xc4, 0x3c, 0xa0, 0x44, 0x78, 0x03, 0xe6, 0x4f, 0x52, 0x4e, 0x75, 0xe6, 0x53, 0xa5, 0x91,
	0x77, 0x39, 0xc6, 0xf8, 0x35, 0x40, 0x44, 0x62, 0x12, 0x50, 0x4e, 0xe3, 0x44, 0x91, 0x5a, 0xf5,
	0xf6, 0x9d, 0xed, 0x56, 0x39, 0xea, 0xb8, 0xfd, 0xce, 0xe1, 0x38, 0xc4, 0x0c, 0x79, 0x9c, 0xda,
	0x7f, 0xe5, 0x6c, 0xbc, 0x82, 0xa5, 0x7f, 0xdc, 0x58, 0x86, 0xfa, 0x19, 0x4d, 0xcb, 0x59, 0x33,
	0x13, 0xaf, 0x42, 0xe3, 0x82, 0x9c, 0x8f, 0xaa, 0x11, 0x0b, 0xf0, 0xa2, 0xf6, 0x1c, 0x69, 0x5f,
	0x11, 0x40, 0x56, 0x28, 0x89, 0x58, 0x98, 0xfc, 0x47, 0x89, 0x2d, 0x10, 0xbd, 0xac, 0xf9, 0x42,
	0x89, 0xf5, 0x4a, 0x89, 0x72, 0x7c, 0x9b, 0x26, 0xa3, 0x73, 0x9e, 0x4d, 0x63, 0xe7, 0x61, 0xd9,
	0x1e, 0xe2, 0x9c, 0x2b, 0x35, 0x29, 0x51, 0x26, 0x56, 0x79, 0x0b, 0xe5, 0x82, 0x2a, 0xb8, 0xf9,
	0x13, 0xc1, 0x5c, 0x29, 0x2c, 0x5e, 0x03, 0xac, 0x1b, 0x96, 0xeb, 0x1c, 0x1f, 0x9a, 0xee, 0x51,
	0xcf, 0x30, 0xf7, 0xf6, 0x7b, 0xa6, 0x21, 0x0b, 0xf8, 0x3e, 0xac, 0x8c, 0x79, 0xe7, 0xa3, 0x6b,
	0x9b, 0xef, 0x8f, 0xcc, 0xbe, 0x23, 0x23, 0xac, 0xc0, 0xea, 0xb4, 0xa3, 0x7f, 0x78, 0xd0, 0xeb,
	0x9b, 0x72, 0x6d, 0xea, 0x57, 0x6f, 0x4c, 0xc7, 0xed, 0x3b, 0x3b, 0x8e, 0x29, 0xd7, 0xf1, 0x43,
	0x78, 0x30, 0xcb, 0x4f, 0x12, 0x45, 0xbc, 0x0e, 0xf7, 0xa6, 0x02, 0x76, 0x8f, 0x1d, 0x53, 0x3f,
	0x30, 0x4c, 0xb9, 0x81, 0x35, 0x50, 0x6f, 0x75, 0x4d, 0xd2, 0xa5, 0xcd, 0xc7, 0x80, 0x67, 0x97,
	0x83, 0x25, 0xa8, 0x1d, 0xbc, 0x95, 0x05, 0x3c, 0x0f, 0xe2, 0xde, 0xce, 0xfe, 0x3b, 0x19, 0x6d,
	0xef, 0x81, 0xa4, 0x1b, 0x96, 0x1d, 0x79, 0xf8, 0x25, 0x2c, 0xea, 0x86, 0xa5, 0xb3, 0x20, 0x18,
	0x85, 0x43, 0x8f, 0x70, 0x8a, 0x97, 0x27, 0xf7, 0x5e, 0xbe, 0x92, 0x8d, 0x59, 0x4a, 0x13, 0xda,
	0xe8, 0x29, 0xda, 0xfd, 0xfc, 0xe3, 0x5a, 0x45, 0x57, 0xd7, 0x2a, 0xfa, 0x7d, 0xad, 0xa2, 0x6f,
	0x37, 0xaa, 0x70, 0x75, 0xa3, 0x0a, 0xbf, 0x6e, 0x54, 0xe1, 0xd3, 0x8e, 0x77, 0x4a, 0x86, 0x61,
	0x40, 0xce, 0x68, 0xdc, 0x61, 0xf1, 0xa0, 0x3b, 0x81, 0x5b, 0x03, 0xd6, 0xf5, 0x99, 0x37, 0x65,
	0x65, 0x07, 0x4d, 0x86, 0x21, 0x8d, 0xbb, 0xd1, 0x49, 0x37, 0xaf, 0x35, 0x60, 0x27, 0x52, 0x6e,
	0x3c, 0xfb, 0x13, 0x00, 0x00, 0xff, 0xff, 0xa2, 0x5b, 0x75, 0x34, 0xcc, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CDMRpcClient is the client API for CDMRpc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CDMRpcClient interface {
	CDMCommunicate(ctx context.Context, opts ...grpc.CallOption) (CDMRpc_CDMCommunicateClient, error)
}

type cDMRpcClient struct {
	cc *grpc.ClientConn
}

func NewCDMRpcClient(cc *grpc.ClientConn) CDMRpcClient {
	return &cDMRpcClient{cc}
}

func (c *cDMRpcClient) CDMCommunicate(ctx context.Context, opts ...grpc.CallOption) (CDMRpc_CDMCommunicateClient, error) {
	stream, err := c.cc.NewStream(ctx, &_CDMRpc_serviceDesc.Streams[0], "/proto.CDMRpc/CDMCommunicate", opts...)
	if err != nil {
		return nil, err
	}
	x := &cDMRpcCDMCommunicateClient{stream}
	return x, nil
}

type CDMRpc_CDMCommunicateClient interface {
	Send(*CDMMessage) error
	Recv() (*CDMMessage, error)
	grpc.ClientStream
}

type cDMRpcCDMCommunicateClient struct {
	grpc.ClientStream
}

func (x *cDMRpcCDMCommunicateClient) Send(m *CDMMessage) error {
	return x.ClientStream.SendMsg(m)
}

func (x *cDMRpcCDMCommunicateClient) Recv() (*CDMMessage, error) {
	m := new(CDMMessage)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// CDMRpcServer is the server API for CDMRpc service.
type CDMRpcServer interface {
	CDMCommunicate(CDMRpc_CDMCommunicateServer) error
}

// UnimplementedCDMRpcServer can be embedded to have forward compatible implementations.
type UnimplementedCDMRpcServer struct {
}

func (*UnimplementedCDMRpcServer) CDMCommunicate(srv CDMRpc_CDMCommunicateServer) error {
	return status.Errorf(codes.Unimplemented, "method CDMCommunicate not implemented")
}

func RegisterCDMRpcServer(s *grpc.Server, srv CDMRpcServer) {
	s.RegisterService(&_CDMRpc_serviceDesc, srv)
}

func _CDMRpc_CDMCommunicate_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(CDMRpcServer).CDMCommunicate(&cDMRpcCDMCommunicateServer{stream})
}

type CDMRpc_CDMCommunicateServer interface {
	Send(*CDMMessage) error
	Recv() (*CDMMessage, error)
	grpc.ServerStream
}

type cDMRpcCDMCommunicateServer struct {
	grpc.ServerStream
}

func (x *cDMRpcCDMCommunicateServer) Send(m *CDMMessage) error {
	return x.ServerStream.SendMsg(m)
}

func (x *cDMRpcCDMCommunicateServer) Recv() (*CDMMessage, error) {
	m := new(CDMMessage)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _CDMRpc_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.CDMRpc",
	HandlerType: (*CDMRpcServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "CDMCommunicate",
			Handler:       _CDMRpc_CDMCommunicate_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "cdm_message.proto",
}

func (m *CDMMessage) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *CDMMessage) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *CDMMessage) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Payload) > 0 {
		i -= len(m.Payload)
		copy(dAtA[i:], m.Payload)
		i = encodeVarintCdmMessage(dAtA, i, uint64(len(m.Payload)))
		i--
		dAtA[i] = 0x1a
	}
	if m.Type != 0 {
		i = encodeVarintCdmMessage(dAtA, i, uint64(m.Type))
		i--
		dAtA[i] = 0x10
	}
	if len(m.TxId) > 0 {
		i -= len(m.TxId)
		copy(dAtA[i:], m.TxId)
		i = encodeVarintCdmMessage(dAtA, i, uint64(len(m.TxId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *TxRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *TxRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *TxRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Parameters) > 0 {
		for k := range m.Parameters {
			v := m.Parameters[k]
			baseI := i
			i -= len(v)
			copy(dAtA[i:], v)
			i = encodeVarintCdmMessage(dAtA, i, uint64(len(v)))
			i--
			dAtA[i] = 0x12
			i -= len(k)
			copy(dAtA[i:], k)
			i = encodeVarintCdmMessage(dAtA, i, uint64(len(k)))
			i--
			dAtA[i] = 0xa
			i = encodeVarintCdmMessage(dAtA, i, uint64(baseI-i))
			i--
			dAtA[i] = 0x32
		}
	}
	if len(m.ByteCode) > 0 {
		i -= len(m.ByteCode)
		copy(dAtA[i:], m.ByteCode)
		i = encodeVarintCdmMessage(dAtA, i, uint64(len(m.ByteCode)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.Method) > 0 {
		i -= len(m.Method)
		copy(dAtA[i:], m.Method)
		i = encodeVarintCdmMessage(dAtA, i, uint64(len(m.Method)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.ContractVersion) > 0 {
		i -= len(m.ContractVersion)
		copy(dAtA[i:], m.ContractVersion)
		i = encodeVarintCdmMessage(dAtA, i, uint64(len(m.ContractVersion)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.ContractName) > 0 {
		i -= len(m.ContractName)
		copy(dAtA[i:], m.ContractName)
		i = encodeVarintCdmMessage(dAtA, i, uint64(len(m.ContractName)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.TxId) > 0 {
		i -= len(m.TxId)
		copy(dAtA[i:], m.TxId)
		i = encodeVarintCdmMessage(dAtA, i, uint64(len(m.TxId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *TxResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *TxResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *TxResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Message) > 0 {
		i -= len(m.Message)
		copy(dAtA[i:], m.Message)
		i = encodeVarintCdmMessage(dAtA, i, uint64(len(m.Message)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Result) > 0 {
		i -= len(m.Result)
		copy(dAtA[i:], m.Result)
		i = encodeVarintCdmMessage(dAtA, i, uint64(len(m.Result)))
		i--
		dAtA[i] = 0x1a
	}
	if m.Code != 0 {
		i = encodeVarintCdmMessage(dAtA, i, uint64(m.Code))
		i--
		dAtA[i] = 0x10
	}
	if len(m.TxId) > 0 {
		i -= len(m.TxId)
		copy(dAtA[i:], m.TxId)
		i = encodeVarintCdmMessage(dAtA, i, uint64(len(m.TxId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintCdmMessage(dAtA []byte, offset int, v uint64) int {
	offset -= sovCdmMessage(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *CDMMessage) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.TxId)
	if l > 0 {
		n += 1 + l + sovCdmMessage(uint64(l))
	}
	if m.Type != 0 {
		n += 1 + sovCdmMessage(uint64(m.Type))
	}
	l = len(m.Payload)
	if l > 0 {
		n += 1 + l + sovCdmMessage(uint64(l))
	}
	return n
}

func (m *TxRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.TxId)
	if l > 0 {
		n += 1 + l + sovCdmMessage(uint64(l))
	}
	l = len(m.ContractName)
	if l > 0 {
		n += 1 + l + sovCdmMessage(uint64(l))
	}
	l = len(m.ContractVersion)
	if l > 0 {
		n += 1 + l + sovCdmMessage(uint64(l))
	}
	l = len(m.Method)
	if l > 0 {
		n += 1 + l + sovCdmMessage(uint64(l))
	}
	l = len(m.ByteCode)
	if l > 0 {
		n += 1 + l + sovCdmMessage(uint64(l))
	}
	if len(m.Parameters) > 0 {
		for k, v := range m.Parameters {
			_ = k
			_ = v
			mapEntrySize := 1 + len(k) + sovCdmMessage(uint64(len(k))) + 1 + len(v) + sovCdmMessage(uint64(len(v)))
			n += mapEntrySize + 1 + sovCdmMessage(uint64(mapEntrySize))
		}
	}
	return n
}

func (m *TxResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.TxId)
	if l > 0 {
		n += 1 + l + sovCdmMessage(uint64(l))
	}
	if m.Code != 0 {
		n += 1 + sovCdmMessage(uint64(m.Code))
	}
	l = len(m.Result)
	if l > 0 {
		n += 1 + l + sovCdmMessage(uint64(l))
	}
	l = len(m.Message)
	if l > 0 {
		n += 1 + l + sovCdmMessage(uint64(l))
	}
	return n
}

func sovCdmMessage(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozCdmMessage(x uint64) (n int) {
	return sovCdmMessage(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *CDMMessage) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowCdmMessage
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: CDMMessage: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: CDMMessage: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TxId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCdmMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCdmMessage
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCdmMessage
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TxId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Type", wireType)
			}
			m.Type = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCdmMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Type |= CDMType(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Payload", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCdmMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthCdmMessage
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthCdmMessage
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Payload = append(m.Payload[:0], dAtA[iNdEx:postIndex]...)
			if m.Payload == nil {
				m.Payload = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipCdmMessage(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthCdmMessage
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *TxRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowCdmMessage
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: TxRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: TxRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TxId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCdmMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCdmMessage
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCdmMessage
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TxId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ContractName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCdmMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCdmMessage
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCdmMessage
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ContractName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ContractVersion", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCdmMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCdmMessage
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCdmMessage
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ContractVersion = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Method", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCdmMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCdmMessage
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCdmMessage
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Method = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ByteCode", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCdmMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthCdmMessage
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthCdmMessage
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ByteCode = append(m.ByteCode[:0], dAtA[iNdEx:postIndex]...)
			if m.ByteCode == nil {
				m.ByteCode = []byte{}
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Parameters", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCdmMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthCdmMessage
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthCdmMessage
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Parameters == nil {
				m.Parameters = make(map[string]string)
			}
			var mapkey string
			var mapvalue string
			for iNdEx < postIndex {
				entryPreIndex := iNdEx
				var wire uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowCdmMessage
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					wire |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				fieldNum := int32(wire >> 3)
				if fieldNum == 1 {
					var stringLenmapkey uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowCdmMessage
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						stringLenmapkey |= uint64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					intStringLenmapkey := int(stringLenmapkey)
					if intStringLenmapkey < 0 {
						return ErrInvalidLengthCdmMessage
					}
					postStringIndexmapkey := iNdEx + intStringLenmapkey
					if postStringIndexmapkey < 0 {
						return ErrInvalidLengthCdmMessage
					}
					if postStringIndexmapkey > l {
						return io.ErrUnexpectedEOF
					}
					mapkey = string(dAtA[iNdEx:postStringIndexmapkey])
					iNdEx = postStringIndexmapkey
				} else if fieldNum == 2 {
					var stringLenmapvalue uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowCdmMessage
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						stringLenmapvalue |= uint64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					intStringLenmapvalue := int(stringLenmapvalue)
					if intStringLenmapvalue < 0 {
						return ErrInvalidLengthCdmMessage
					}
					postStringIndexmapvalue := iNdEx + intStringLenmapvalue
					if postStringIndexmapvalue < 0 {
						return ErrInvalidLengthCdmMessage
					}
					if postStringIndexmapvalue > l {
						return io.ErrUnexpectedEOF
					}
					mapvalue = string(dAtA[iNdEx:postStringIndexmapvalue])
					iNdEx = postStringIndexmapvalue
				} else {
					iNdEx = entryPreIndex
					skippy, err := skipCdmMessage(dAtA[iNdEx:])
					if err != nil {
						return err
					}
					if (skippy < 0) || (iNdEx+skippy) < 0 {
						return ErrInvalidLengthCdmMessage
					}
					if (iNdEx + skippy) > postIndex {
						return io.ErrUnexpectedEOF
					}
					iNdEx += skippy
				}
			}
			m.Parameters[mapkey] = mapvalue
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipCdmMessage(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthCdmMessage
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *TxResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowCdmMessage
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: TxResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: TxResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TxId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCdmMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCdmMessage
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCdmMessage
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TxId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Code", wireType)
			}
			m.Code = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCdmMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Code |= ContractResultCode(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Result", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCdmMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthCdmMessage
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthCdmMessage
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Result = append(m.Result[:0], dAtA[iNdEx:postIndex]...)
			if m.Result == nil {
				m.Result = []byte{}
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Message", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowCdmMessage
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthCdmMessage
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthCdmMessage
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Message = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipCdmMessage(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthCdmMessage
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipCdmMessage(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowCdmMessage
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowCdmMessage
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowCdmMessage
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthCdmMessage
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupCdmMessage
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthCdmMessage
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthCdmMessage        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowCdmMessage          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupCdmMessage = fmt.Errorf("proto: unexpected end of group")
)
